module.exports = {
    PFP_HEIGHT: 1,
    PFP_LEFT_MARGIN: 32 / 80,
    PFP_RIGHT_MARGIN: 33 / 80,
    USERNAME_HEIGHT: 23 / 80,
    CONTENT_HEIGHT: 23 / 80,
    TIMESTAMP_HEIGHT: 17.25 / 80,
    PFP_USERNAME_VERTICAL_DISTANCE: 7 / 80,
    PFP_TIMESTAMP_VERTICAL_DISTANCE: 68 / 80,
    PFP_CONTENT_VERTICAL_DISTANCE: 30 / 80,
    USERNAME_CONTENT_VERTICAL_DISTANCE: 22 / 80,
    USERNAME_TIMESTAMP_HORIZONTAL_DISTANCE: 18 / 80
};
